// locale/zh.js
export default ({
   hello: '你好，{name}',
   "Apply":"应用",    "Reset":"重置",
   "Add":"新增",     "Edit":"编辑","edit":"编辑",     "Delete":"删除","delete":"删除",    "Save":"保存", "save":"保存",
   "Network Center":"网络中心",
   "ReadySHARE":"文件共享",
   "vPort":"端口",
   "Diagnosis":"症断",
   "Setting":"设置",         "setting":"设置",
   "state":"状态",           "State":"状态",
   "wireless":"无线",        "Wireless":"无线",
   "Internet":"互联网",
   "localNetwork":"本地网络",     "Local Network":"本地网络",
   "parentalCtrl":"家长控制",
   "flowCtrl":"流量控制",         "Flow Control":"流量控制",
   "security":"安全性",          "Security":"安全性",
   "noticeSettings":"通知设置",
   "management":"管理",
   "Remote Router":"远程路由器",
   "vPath":"路径",

   "vPath packs":"路径包",
   "payment":"支付",

   "Manage Server":"管理服务器",
   "Management Goal":"管理目标",
   "Syslog":"系统日志",                         "System log":"系统日志",
   "Address":"地址",
   "Port":"端口",
   "test":"测试",
   "Level":"等级",
   "Enable":"启动",         "Enabled":"已启动",     "Closed":"已关闭",
   "Expiration date":"到期时间",
   "Please click to pay":"支付请点击",
   "close":"关闭",        "Close":"关闭",
   "refresh":"刷新",
   "Virtual":"虚拟", "virtual":"虚拟",
   "Add New":"添加",
   "Boot Nodes":"引导节点",
   "Remote Virtual IP":"远程虚拟IP",
   "Remote Subnet":"远程子网",
   "Link State":"链路状态",
   "delay":"延时",
   "description":"描述",
   "Please input keywords or domain or URL":"请输入关键字或域名或URL",
   "vPath_title":"来自vPort{idNum}的域名的流量将通过所选的vProxy路由。",
   "domain":"域名",
   "proxy":"代理",
   "vPathPacks_title":"vPathPacks:请选择一个要编辑的vPathPack",
   "Already Online":"已联机",
   "Gateway":"网关",
   "Server":"服务器",
   "Name":"名称",
   "Safe Mode":"安全模式",
   "Device List":"设备列表",
   "Memory":"内存",
   "Enable wireless broadcast":"启用无线广播",
   "Show":"显示",
   "Hide":"隐藏",
   "Security Level":"安全级别",
   "Security Mode":"安全模式",
   "Guest Network":"访客网络",
   "Filter":"过滤器",
   "Password":"密码","password":"密码",
   "Wireless Mode":"无线模式",
   "Advanced Options":"高级选项",

   "wps_tab_desc":"您可以使用WPS(Wi-Fi Protected Setup)以在Router与无线客户端之间共享无线密钥，并通过以下方法之一安全地建立无线网络。",
   "Connection State":"连接状态",
   "Ready":"已就绪",
   "Connection Type":"连接类型",
   "By Push Button":"通过推送按钮",
   "Target":"目标机",
   "Mask":"掩码",
   "vProxy":"代理",

   "workMode_desc":"您如何设置Router的网络映射？要了解更多信息，请参考SRM帮助。",
   "Plan":"计划",                       "Work Mode":"工作模式",
   "Update And Reset":"更新和还原",     "Default Port Number":"默认端口号",
   "System Name":"系统名称",            "Region Options":"区域选项",
   "Using State":"使用状态",
   "Enable SSH Functionality":"启动SSH功能",
   "Wireless Router":"无线路由器",
   "Wireless access point":"无线接入点",
   "Wireless client":"无线客户端",
   "Firewall":"防火墙",        "firewall":"防火墙",
   "Auto Block":"自动封锁",
   "Certificate":"证书",
   "Email":"电子邮件",
   "Message":"短信",
   "Push Service":"推送服务",   "Service":"服务",
   "Advanced Setting":"高级设置",

   //互联网
   "Link":"链接",
   "QuickConnect & DDNS":"快速连接和DDNS",
   "Port Forwarding":"端口转发",
   "Port Trigger":"端口触发",
   "Tunnel":"隧道",
   "3G And 4G":"3G和4G",
   "You can set up the Internet connection here. Your connection type is determined by the network environment. Please consult ISP to get the help you need.":"您可在此设置Internet连接。您的连接类型由网络环境决定。请咨询ISP以获取所需的帮助。",
   "Set as default gateway":"设为默认网关",
   "Automatic":"自动",
   "Manual":"手动",
   "Connect to your router everywhere":"随处连接到您的路由器",
   "Internet_DDNS_desc":"QuickConnect 能够让您在任何地方轻松的连接到路由器，只需启动下方的QuickConnect并注册一组账户即可完成。",
   "Enable DDNS to enable users to connect to servers with registered host names.":"启用支持DDNS让用户以注册的主机名称连接服务器。",
   "Advanced Setting":"高级设置",
   "Full Name":"姓名",
   "Trigger Port":"触发器端口",
   "Inbound Port":"入站端口",
   "Source IP":"来源IP",
   "Communication Protocol":"通讯协议",
   "Rule":"规则",
   "Target Device":"目标设备",
   "Private IP Address":"专用IP地址",
   "Common Port":"公共端口",
   "Private Port":"专用端口",
   "DMZ allows you to display a server on the Internet so that all inbound packets will redirect to the server.":"DMZ可让您将一台服务器显示在Internet上，以使所有的进站数据包都将重新导向到该服务器。",
   "This is very useful when the server is running applications that use an uncertain inbound port.":"这在服务器正在运行那些使用不确定入站端口的应用程序时非常有用。",
   "Starting Tunnel can use IPv6 communication protocol in IPv4 network environment.":"启动Tunnel 可在IPv4网络环境里使用IPv6通讯协议。",
   "DMZ Host IP Address":"DMZ主机IP地址",
   "External address":"外部地址",
   "Anonymous online":"匿名联机",
   "Online with current accounts":"以现有账号联机",
   "User Name":"用户名",
   "":"",
   "":"",


   "":"",
   //本地网络
   "Routine":"常规",
   "Static Route":"静态路由",
   "Client":"客户端",
   "IPTV And VoIP":"IPTV和VoIP",
   "Start IP Address":"起始IP地址",
   "End IP Address":"结束IP地址",
   "Rent Address Time(Unit:s)":"地址租用时间(单位:秒)",
   "Transfer to known DHCP Server":"转送已知DHCP服务器",
   "Disabled":"已停用",   "Disable":"禁用",
   "":"",

   //管理
   "Present Time":"现在时间",
   "Time Zone":"时区",
   "Server Address":"服务器地址",
   "Country":"国家",
   "choose_country_desc":"请选择您的当前位置以确保路由器有完整的功能。",
   "choose_country_hint":"<span style='color:red;'>重要</span>:错误的国家设置可能导致法律问题。",
   "Interface display language":"界面显示语言",
   "choose_language_desc":"选择默认的界面显示语言。（用户可以在选项页面中更改个人的显示语言。）",
   "China":"中国",       "Chinese":"中文",
   "Others":"其他国家",
   "English":"英语",
   "Immediate updates":"立即更新",

   //服务
   "Terminal":"终端机",
   "Enable SNMP Service":"启动SNMP服务",
   "Device Name":"设备名",
   "Device Location":"设备位置",
   "Contact Way":"联系方式",
   "Community":"社群",
   "User Account":"用户帐号",

   //RSM设置
   "Redirect the HTTP connection automatically to HTTPS":"将HTTP连接自动重新导向到HTTPS",
   "You can import certificates on the certificate page.":"您可以导入证书页面上的证书。",
   "Enabling HSTS will force browsers to use secure connections.":"启用HSTS会强制浏览器使用安全连接。",
   "Enable Windows network discovery":"启用Windows网络发现",
   "After this option is enabled,Windows network discovery will be able to search the Router.":"启用此选项后，Windows网络发现将可搜索到路由器。",
   "Allow external access to SRM":"允许外部访问SRM",
   "Starting this option allows external access to SRM through HTTP/HTTPS ports (such as: 8000 and 8001).":"启动此选项可让外部通过HTTP/HTTPS端口（如：8000和8001访问SRM）。",

   //更新和还原
   "System Update":"系统更新",
   "Product model":"产品型号",
   "Version":"版本",
   "Version can be downloaded":"{version} 版本可下载，（最新功能）",
   "Manual Update":"手动更新",
   "Update Setting":"更新设置",
   "Download":"下载",
   "Configuring backup and restore":"配置备份和还原",
   "Backup Configuration":"备份配置",
   "Backup router configuration and save configuration file(.dss) to your computer.":"备份路由器配置并将配置文件（.dss）保存到您的计算机。",
   "Restore the backup configuration or restore the router to factory settings.":"还原备份配置或恢复路由器至出厂设置值。",
   "Restore Configuration":"还原配置",
   "Restore Factory Settings":"恢复出厂设置值",

   //电子邮件
   "email_desc":"当状态改变或系统发生错误时，启动电子邮件通知服务通过电子邮件接收通知消息。",
   "Enable email notification":"启动电子右键通知",
   "Recipient":"收件人",
   "Subject prefix":"主题前缀",
   "Service provider":"服务供应商",
   "Send welcome messages to new users":"向新用户发送欢迎消息",
   "Log in to Gmail":"登录到Gmail",
   "Send test email":"发送测试电子邮件",

   //安全性
   "security_desc":"设置SRM包含网页应用程序在浏览器上的自动注销时间。",
   "Wait timeout(min)":"等候超时（分）",
   "Ignore IP checks to enhance browser compatibility":"忽略IP检查来加强浏览器的兼容性",
   "Enabling this option provides better compatibility for browsers using proxy servers, but reduces the security level.":"启用此选项会为使用代理服务器的浏览器提供较好的兼容性，但会降低安全级别。",
   "Improve the protection of Cross Site Request Forgery attack.":"提高对跨网站请求伪造攻击的保护。",
   "SRM is not allowed to be embedded by iFrame":"不允许SRM被iFrame嵌入",
   "Allow specific sites to embed SRM using iFrame.":"允许特定网站使用iFrame嵌入SRM。",
   "Dos Protect":"Dos 保护",
   "Allowed websites":"允许的网站",
   "Denial of service(Dos) protection helps prevent malicious attacks on Internet.":"拒绝服务(Dos)保护有助于防止Internet上的恶意攻击。",
   "Enable Dos protection":"启用Dos保护",
   "VPN Pass-through":"VPN 通过",
   "Please select the option according to the VPN protocol used by the VPN client, so that the VPN client traffic can be passed through the router.":"请根据VPN客户端使用的VPN协议勾选选项，以使VPN客户端流量可通过路由器。",
   "PPTP Pass-through":"PPTP 通过",

   //流量控制
   "Monitor":"监控",
   "Routine Setting":"常规设置",
   "Custom Speed":"自定义速度",
   "High Priority":"高优先级",

   "":"",
   "":"",
   "":"",
   "":"",
   "":"",
   "":"",
   "":"",
   "":"",
   "":"",



 });
